tap "aquasecurity/trivy"
tap "atomicjar/tap"
tap "aws/tap"
tap "buo/cask-upgrade"
tap "busser/tap"
tap "dopplerhq/cli"
tap "hashicorp/tap"
tap "homebrew/command-not-found"
tap "hudochenkov/sshpass"
tap "padok-team/tap"
tap "romankurnovskii/cask"
tap "schniz/tap"
tap "stripe/stripe-cli"
tap "tylerbrock/saw"
brew "act"
brew "certifi"
brew "python@3.12"
brew "ansible"
brew "ansible-lint"
brew "antigen"
brew "webp"
brew "awk"
brew "aws-sam-cli"
brew "awscli"
brew "bat"
brew "caddy", restart_service: :changed
brew "glib"
brew "cmake"
brew "ruby", link: true
brew "cocoapods"
brew "coreutils"
brew "curl", link: true
brew "dfu-util"
brew "doctl"
brew "dotenv-linter"
brew "folly"
brew "fizz"
brew "wangle"
brew "fbthrift"
brew "fb303"
brew "edencommon"
brew "eza"
brew "fastlane"
brew "fnm"
brew "fzf"
brew "gh"
brew "harfbuzz"
brew "git"
brew "git-delta"
brew "glances"
brew "gnupg"
brew "go"
brew "pkgconf"
brew "gobject-introspection"
brew "helm"
brew "icu4c@76"
brew "libheif"
brew "imagemagick"
brew "iproute2mac"
brew "jq"
brew "k6"
brew "kubernetes-cli"
brew "lsd"
brew "mas"
brew "mkcert"
brew "mvfst"
brew "ncdu"
brew "nmap"
brew "nss"
brew "openjdk@11"
brew "parquet-cli"
brew "pinentry-mac"
brew "psqlodbc"
brew "python@3.8"
brew "qrencode"
brew "ruby-build"
brew "rbenv"
brew "rclone"
brew "rover"
brew "ruby@3.1"
brew "scc"
brew "screen"
brew "starship"
brew "stow"
brew "swiftformat"
brew "telnet"
brew "terragrunt"
brew "tig"
brew "tree"
brew "vim"
brew "wakeonlan"
brew "watch"
brew "watchman"
brew "wget"
brew "whalebrew"
brew "wimlib"
brew "xxh"
brew "ykpers"
brew "zoxide"
brew "zsh"
brew "zsh-completions"
brew "dopplerhq/cli/doppler"
brew "hashicorp/tap/terraform"
brew "hudochenkov/sshpass/sshpass"
brew "tylerbrock/saw/saw"
cask "1password"
cask "1password-cli"
cask "alfred"
cask "android-commandlinetools"
cask "android-platform-tools"
cask "android-studio"
cask "appcleaner"
cask "arc"
cask "brave-browser"
cask "charles"
cask "clickup"
cask "cryptomator"
cask "cyberduck"
cask "discord"
cask "dynobase"
cask "figma"
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-lato"
cask "font-monaspace"
cask "font-ostrich-sans"
cask "font-raleway"
cask "ghostty"
cask "google-chrome"
cask "hiddenbar"
cask "insomnia"
cask "iterm2"
cask "keka"
cask "linear-linear"
cask "neat"
cask "notion"
cask "obsidian"
cask "ollamac"
cask "orangedrangon-android-messages"
cask "orbstack"
cask "p4v"
cask "pingnoo"
cask "postman"
cask "private-internet-access"
cask "resilio-sync"
cask "rustdesk"
cask "soqlxplorer"
cask "spotify"
cask "steam"
cask "tableplus"
cask "there"
cask "tradingview"
cask "ultimaker-cura"
cask "unetbootin"
cask "visual-studio-code"
cask "warp"
cask "zed"
cask "zen-browser"
cask "zoom"
mas "1Password for Safari", id: 1569813296
mas "Affinity Designer", id: 824171161
mas "Affinity Photo", id: 824183456
mas "Amphetamine", id: 937984704
mas "Copilot", id: 1447330651
mas "DaisyDisk", id: 411643860
mas "Dato", id: 1470584107
mas "GIF Brewery 3", id: 1081413713
mas "HP Smart", id: 1474276998
mas "Keynote", id: 409183694
mas "LanScan", id: 472226235
mas "Magnet", id: 441258766
mas "Medis", id: 1579200037
mas "MQTT Explorer", id: 1455214828
mas "Numbers", id: 409203825
mas "Paprika Recipe Manager 3", id: 1303222628
mas "UTC Time", id: 1538245904
mas "WhatsApp", id: 310633997
mas "WhatsApp", id: 1147396723
mas "WiFi Explorer", id: 494803304
mas "WireGuard", id: 1451685025
mas "Xcode", id: 497799835
