#!/usr/bin/env bash

set -e
echo "$OSTYPE $(uname)"

case $(uname) in
Darwin)
  xcode-select --install | 2>/dev/null
  ;;
Linux)
  sudo apt update
  sudo apt upgrade -y
  export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
  ;;
esac

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

brew reinstall git stow gpg antigen

brew unlink git gpg
brew link git gpg

cd dots
stow -t ~ .

# ignore any changes to these files
# they do need to be added to the gitignore after they are first tracked and comitted
git update-index --assume-unchanged ./dots/.aws

# To track them again:
# git update-index --no-assume-unchanged ./dots/.aws

chmod 700 ~/.config/op

brew bundle install --global
