#!/usr/bin/env bash

set -e
echo "$OSTYPE $(uname)"

case $(uname) in
Darwin)
  xcode-select --install | 2>/dev/null
  ;;
Linux)
  sudo apt update
  sudo apt upgrade -y
  export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
  ;;
esac

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

brew reinstall git stow gpg antigen

brew unlink git gpg
brew link git gpg

cd dots
stow -t ~ .

chmod 700 ~/.config/op

brew bundle install --global
