tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "schniz/tap"
tap "tylerbrock/saw"
cask "adoptopenjdk8"
brew "ansible"
brew "awk"
brew "aws-elasticbeanstalk"
brew "awscli"
brew "bat"
brew "gettext"
brew "coreutils"
brew "credstash"
brew "curl"
brew "dfu-util"
brew "doctl"
brew "elixir"
brew "exercism"
brew "ffmpeg"
brew "git"
brew "gnupg"
brew "gnupg@1.4"
brew "helm"
brew "imagemagick@6"
brew "kompose"
brew "kubernetes-cli", link: false
brew "mas"
brew "ncdu"
brew "psqlodbc"
brew "ruby", link: true
brew "telnet"
brew "terraform"
brew "tree"
brew "vim"
brew "wakeonlan"
brew "watch"
brew "watchman"
brew "yarn"
brew "z"
brew "zsh"
brew "zsh-completions"
brew "schniz/tap/fnm"
brew "tylerbrock/saw/saw"
cask "1password"
cask "alfred"
cask "android-messages"
cask "android-platform-tools"
cask "appcleaner"
cask "atom"
cask "authy"
cask "balenaetcher"
cask "balsamiq-mockups"
cask "brave-browser"
cask "caffeine"
cask "caprine"
cask "charles"
cask "cyberduck"
cask "dash"
cask "deckhub"
cask "discord"
cask "divvy"
cask "docker"
cask "dozer"
cask "drawio"
cask "dropbox"
cask "expressions"
cask "firefox-developer-edition"
cask "font-fira-code"
cask "font-firacode-nerd-font"
cask "franz"
cask "gitify"
cask "google-chrome"
cask "graphql-playground"
cask "insomnia"
cask "iterm2"
cask "keka"
cask "keybase"
cask "little-snitch"
cask "ngrok"
cask "p4v"
cask "paw"
cask "plex-media-player"
cask "postico"
cask "postman"
cask "private-internet-access"
cask "realm-studio"
cask "rescuetime"
cask "resilio-sync"
cask "sensei"
cask "signal"
cask "slack"
cask "snowflake-snowsql"
cask "soqlxplorer"
cask "spotify"
cask "spotify-notifications"
cask "steam"
cask "sublime-text"
cask "tableplus"
cask "teamviewer"
cask "ultimaker-cura"
cask "visual-studio-code"
cask "vlc"
mas "Affinity Photo", id: 824183456
mas "Airmail", id: 918858936
mas "Amphetamine", id: 937984704
mas "Boom 2", id: 948176063
mas "CleanMyDrive 2", id: 523620159
mas "Day One", id: 1055511498
mas "Deliveries", id: 924726344
mas "Fantastical", id: 975937182
mas "Final Cut Pro", id: 424389933
mas "GIF Brewery 3", id: 1081413713
mas "Jump Desktop", id: 524141863
mas "LanScan", id: 472226235
mas "Magnet", id: 441258766
mas "Medis", id: 1063631769
mas "Numbers", id: 409203825
mas "Paprika Recipe Manager 3", id: 1303222628
mas "Parcel", id: 639968404
mas "PDF Expert", id: 1055273043
mas "Spark", id: 1176895641
mas "Todoist", id: 585829637
mas "Trello", id: 1278508951
mas "Tweetbot", id: 557168941
mas "Vimeo", id: 1356686763
mas "WhatsApp", id: 1147396723
mas "WiFi Explorer Lite", id: 1408727408
mas "WireGuard", id: 1451685025
mas "Xcode", id: 497799835
