tap "homebrew/core"
tap "homebrew/bundle"
tap "caskroom/fonts"
tap "caskroom/versions"
tap "caskroom/cask"

cask "java"

brew "awk"
brew "aws-elasticbeanstalk"
brew "coreutils"
brew "couchdb"
brew "git"
brew "ffmpeg"
brew "gnupg"
brew "gnupg@1.4"
brew "mas"
brew "ncdu"
brew "python3"
brew "ruby"
brew "telnet"
brew "tree"
brew "vim"
brew "yarn"
brew "z"
brew "zsh"
brew "zsh-completions"

cask "1password"
cask "alfred"
cask "android-platform-tools"
cask "atom"
cask "caffeine"
cask "dash"
cask "deckhub"
cask "discord"
cask "divvy"
cask "dropbox"
cask "gitify"
cask "google-chrome"
cask "iterm2"
cask "keka"
cask "keybase"
cask "ngrok"
cask "p4merge"
cask "plex-media-player"
cask "resilio-sync"
cask "slack"
cask "spotify"
cask "spotify-notifications"
cask "steam"
cask "sublime-text"
cask "teamviewer"
cask "visual-studio-code"
cask "caskroom/fonts/font-fira-code"

mas "Affinity Photo", id: 824183456
mas "Airmail 3", id: 918858936
mas "DaisyDisk", id: 411643860
mas "Deliveries", id: 924726344
mas "Fantastical 2", id: 975937182
mas "Gemini 2", id: 1090488118
mas "GIF Brewery 3", id: 1081413713
mas "Magnet", id: 441258766
mas "Trello", id: 1278508951
mas "WhatsApp", id: 1147396723
