# zmodload zsh/zprof
export ZSH=$HOME/.oh-my-zsh
export NVM_LAZY_LOAD=true

ZSH_THEME="robbyrussell"

COMPLETION_WAITING_DOTS="true"

HIST_STAMPS="mm/dd/yyyy"

plugins=(
    npm
    osx
    k
    git
    docker-compose
    zsh-autosuggestions
    zsh-syntax-highlighting
    colored-man-pages
    zsh-nvm
)

source $ZSH/oh-my-zsh.sh

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

[ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

source ~/.profile
# zprof
