# zmodload zsh/zprof
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="robbyrussell"

COMPLETION_WAITING_DOTS="true"

HIST_STAMPS="mm/dd/yyyy"

plugins=(
    npm
    osx
    k
    git
    docker-compose
    zsh-autosuggestions
    zsh-syntax-highlighting
    colored-man-pages
)

source $ZSH/oh-my-zsh.sh

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

source ~/.profile
# zprof

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /Users/rizowski/.config/yarn/global/node_modules/tabtab/.completions/serverless.zsh ]] && . /Users/rizowski/.config/yarn/global/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /Users/rizowski/.config/yarn/global/node_modules/tabtab/.completions/sls.zsh ]] && . /Users/rizowski/.config/yarn/global/node_modules/tabtab/.completions/sls.zsh
# tabtab source for slss package
# uninstall by removing these lines or running `tabtab uninstall slss`
[[ -f /Users/rizowski/.config/yarn/global/node_modules/tabtab/.completions/slss.zsh ]] && . /Users/rizowski/.config/yarn/global/node_modules/tabtab/.completions/slss.zsh
